[package]
name = "markdown-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
napi-build = "2.3.1"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }
comrak = "0.49.0"

[[bench]]
name = "bench-in-rust"
harness = false

[dependencies]
figment = { version = "0.10", features = ["toml", "env"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0.17"
ammonia = "4.1.2"
lazy_static = "1.5.0"
regex = "1.10.5"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

pulldown-cmark = { version = "0.13.0", default-features = false, features = ["html"] }
pulldown-cmark-toc = "0.7.0"
syntect = "5.3.0"
v_htmlescape = "0.15.8"

napi-derive = "3.4.1"

napi = { version = "3.7.1", default-features = false, features = ["napi4"] }
