[package]
name = "wdocs-search"
version = "0.1.0"
edition = "2021"

[build-dependencies]
napi-build = { version = "2.3.1", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rayon = "1.11.0"
dashmap = "6.1.0"
rustc-hash = "2.1.1"
napi = { version = "3.8.2", default-features = false, features = ["napi4"] }
napi-derive = "3.5.1"
fst = "0.4.7"
roaring = "0.11.3"

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

# Error Handling
anyhow = "1.0.100"
thiserror = "2.0.17"
rust-stemmers = "1.2.0"

# Async Runtime
tokio = { version = "1.49.0", features = ["full"] }

# Logging & Tracing
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["json", "env-filter"] }

[dev-dependencies]
criterion = { version = "0.8.1", features = ["async_tokio"] }
tokio = { version = "1.49.0", features = ["full"] }
serde_json = "1.0.149"
tantivy = "0.25.0"
minisearch = "0.1.1"
meilisearch-sdk = "0.32.0"

[profile.release]
lto = true

[[bench]]
name = "bench-in-rust"
harness = false


