# Default tracing configuration

[default]
level = "info"

[default.format]
full = false
with_target = false
with_thread_ids = false
with_thread_names = false

[default.file]
path = "document-parsers.log"
rotation = "never"
